### ISSUE TITLE
Dismiss opened cell upon responder change

### ISSUE THREAD

**Issue by sedwo** [John-Lluch/SWRevealTableViewCell#5]
I swipe to open one cell.
I can then drag another cell, while the first cell is still opened.
Tapping outside of the cell, or even on the opened cell (not the buttons) doesn't dismiss the opened cell.

I'm thinking it should respond like the default mail app swipes where it doesn't allow me to work on another cell until the original one is complete dismissed.

**Comment by John-Lluch** [comment]
The example already dismisses cells when you reveal another one. This is also shown in the video I just uploaded to YouTube. http://youtu.be/jlaWQsWinoU

If you want cells to be dismissed before, i.e at the time of clicking on another one, then you can do so. The class is not meant to be a precooked mail app emulator. Instead it is designed for total flexibility and it incorporates methods and delegates to fully control a lot of its behavior.

Note that it is the example that dismisses revealed cells when another one is revealed, not the SWRevealTableViesCell class itself, because the cell does not have a notion of its tableView. This is by design.

I hope this helps.

Thanks

**Comment by sedwo** [comment]
I've been spoiled by controls like [MSCMoreOptionTableViewCell](https://github.com/scheinem/MSCMoreOptionTableViewCell) that maintain the mail app consistency of cell swiping.  :|

**Comment by John-Lluch** [comment]
Hi sedwo, 

I had a look at the MSCMoreOptionTableViewCell source code and found it to be extremely hacky. What it does is to add a "more" button next to Apple's "delete" button by digging into the UITableViewCell view hierarchy. That's very unconventional because it strongly relies on private Apple's UITableViewCell implementation that the author must have reverse-engineered or figured out by testing.

Actually, the code is funny to look at because there's an interesting number of hacks in it. Some features like the 'tap to dismiss' and Apple provided tableView delegates work out of the box because the delete button is actually Apple's one (!).

On the negative side its dependency to an undocumented (already existing) view hierarchy does not leave a lot of room for custom behaviors. For example you can't open or dismiss a cell programmatically. Of course if you just want minimal configuration it's perfect.

On iOS8, Apple will be providing a way to add left and right buttons to cells behaving like iOS7 mail. However, the SWRevealTableViewCell provides a highly customizable way to emulate iOS8 mail app on both iOS7 and iOS8. I hope this has some sense. :-)
