### ISSUE TITLE
cell ignores performsActionOnRightOverdraw setting?

### ISSUE THREAD

**Issue by dmiedema** [John-Lluch/SWRevealTableViewCell#8]
I have a custom UITableViewCell inheriting from `SWRevealTableViewCell` that even though I set `cell.performsActionOnRightOverdraw = NO; cell.performsActionOnLeftOverdraw = NO;` it still seems to perform the action when the cell is pulled 'too far' to the left (revealing right items).

My `cellForRowAtIndexPath` is essentially

``` objc
HHAPropertyViewingListTableViewCell *cell = (HHAPropertyViewingListTableViewCell *)[tableView dequeueReusableCellWithIdentifier:ReuseIdentifier forIndexPath:indexPath];
    cell.selectionStyle = UITableViewCellSelectionStyleNone;
    /*
        code omitted because really its just setting labels and things, really nothing of interest happens here but if you _really_ care i can post it
    */
    cell.dataSource = self;
    cell.performsActionOnRightOverdraw = NO;
    cell.performsActionOnLeftOverdraw = NO;

    return cell;
```

For my right items I've got this lovely (thank for for the iOS 8 like API, even if it wasn't intentional)

``` objc
#pragma mark - SWRevealTableViewCellDataSource
- (NSArray *)rightButtonItemsInRevealTableViewCell:(SWRevealTableViewCell *)revealTableViewCell {
    SWCellButtonItem *delete = [SWCellButtonItem itemWithTitle:NSLocalizedString(@"Delete", @"Delete") handler:^BOOL(SWCellButtonItem *item, SWRevealTableViewCell *cell) {
        NSIndexPath *indexPath = [self.tableView indexPathForCell:cell];
        DDLogDebug(@"Delete indexPath - %@", indexPath);
        [self tableView:self.tableView deleteRowAtIndexPath:indexPath];
        return YES;
    }];

    SWCellButtonItem *openInMaps = [SWCellButtonItem itemWithTitle:NSLocalizedString(@"Maps", @"Maps") handler:^BOOL(SWCellButtonItem *item, SWRevealTableViewCell *cell) {
        NSIndexPath *indexPath = [self.tableView indexPathForCell:cell];
        DDLogDebug(@"Maps indexPath - %@", indexPath);
        HHAUserListProperty *property = self->_properties[indexPath.row];
        [[HHAMapAndDistanceHelpers mapItemForUserListProperty:property] openInMapsWithLaunchOptions:@{}];
        return YES;
    }];

    SWCellButtonItem *move = [SWCellButtonItem itemWithTitle:NSLocalizedString(@"Move", @"Move") handler:^BOOL(SWCellButtonItem *item, SWRevealTableViewCell *cell) {
        NSIndexPath *indexPath = [self.tableView indexPathForCell:cell];
        DDLogDebug(@"Move indexPath - %@", indexPath);
        [self movePropertyAtIndexPath:indexPath];
        return NO;
    }];

    CGFloat width = 75;

    delete.backgroundColor = [UIColor redColor];
    delete.tintColor = [UIColor whiteColor];
    delete.width = width;

    openInMaps.backgroundColor = [UIColor houseHappy];
    openInMaps.tintColor = [UIColor whiteColor];
    openInMaps.width = width;

    move.backgroundColor = [UIColor colorWithWhite:0.7 alpha:1.0];
    move.tintColor = [UIColor whiteColor];
    move.width = width;

    return @[delete, openInMaps, move];
}
```

So when i 'pull too far' on the cell to the left revealing the right items, it performs the `delete` action. However, i'd like to turn that off (on an iPad its _way_ too easy to trigger that pull) but the cell doesn't seem to listen.

Am i configuring that setting in the incorrect location by chance? Or perhaps missing something?

Thanks

**Comment by maddoggy1979** [comment]
I am having the same trouble.

From what I can tell, the default behaviour should not performa action on overdraw, based on the SWCellRevealModeNormal, which brings with it the default setting of `cell.performsActionOnRightOverdraw = NO;`
But, it doesn't seem to work that way.

This is from the `SWRevealTableViewCell.m` file.

``` objective-c
- (void)_initProperties
{
    _frontViewPosition = SWCellRevealPositionCenter;
    _leftViewPosition = SWCellRevealPositionCenter;
    _rightViewPosition = SWCellRevealPositionCenter;
    _quickFlickVelocity = 150.0f;
    _revealAnimationDuration = 0.5;
    _animationQueue = [NSMutableArray array];
    [self setCellRevealMode:SWCellRevealModeNormal];
}
```

As a related item, setting the `quickFloatVelocity` to 10,000.0f also didn't stop the quick flick delete action.

This is the only thing bugging me at the moment - otherwise it's been easy and quick to implement with no fuss.

``` objective-c
// Defines whether the handler block of the first item must invoked on user overdraw.
// When this is set to YES user pan action is acompained with an animation similar to the delete action of iOS8 mail.
// This property is only honored when XXCascadeReversed is also set to YES
@property (nonatomic) BOOL performsActionOnRightOverdraw;   // default is NO
@property (nonatomic) BOOL performsActionOnLeftOverdraw;    // default is NO

// Velocity required for the controller to toggle its reveal state based on a swipe movement, default is 150
// You can disable velocity triggered swipe by seting this to a very high number
@property (nonatomic) CGFloat quickFlickVelocity;
```

**Comment by John-Lluch** [comment]
Hi all, 

These issues (or part of them) should be solved on version v0.3.1 that I submitted yesterday night (euro time). The intended behavior is this:
- Right/Left cascadeReversed is meant to change the way items appear on the edges, Top to bottom or vice-versa. Reversed=YES attempts to emulate iOS8 mail. Reversed=NO attempts to display the items in a way that they appear to be completely behind the cell.
- performsActionOnOverdaw is only supported with cascadeReversed = YES, otherwise it is ignored.
- setting  bounceBackOnOverdraw to YES, will make the cell to always bounce back on overdraw regardless of the remaining settings, or action return values.
- When cascadeReversed is YES then performsActionOnOverdaw is honored. If you set performsActionOnOverdaw to YES then item actions will fire. The action return value determines whether the cell bounces back to center position. However if you had bounceBackOnOverdraw to YES the cell will always bounce back to center regardless of the action return value.

I think this is how it behaves now. Please let me know in case it is not.

Thanks !

**Comment by John-Lluch** [comment]
Hi, I just verified the correctness of my post just above and I found a remaining bug :-/  so I updated it to v0.3.2. 
I think it should be all ok now.
Thanks.

**Comment by maddoggy1979** [comment]
That worked for me - no SWRevealTableViewCell properties needed to be set in my cellForRowAtIndexPath method. It just works out of the box now.
Thanks.

**Comment by John-Lluch** [comment]
My pleasure.

**Comment by dmiedema** [comment]
v0.3.2 has fixed the issue for me as well.
Thanks!
